security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        # Configurez ici votre fournisseur d'utilisateurs, par exemple votre entité Utilisateur
        my_entity_provider:
            entity:
                class: 'App\Entity\Utilisateur'
                property: 'email' # Remplacez par la propriété de votre entité utilisée pour l'authentification
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: my_entity_provider # Utilisez le fournisseur d'utilisateurs configuré
            form_login:
                login_path: login
                check_path: login
                default_target_path: home_client
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
            logout:
                path: app_logout
                target: login
            session_fixation_strategy: migrate

    access_control:
        # Ajoutez ici vos règles d'accès

