security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto
            cost: 12
    providers:
        utilisateurs:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: utilisateurs
            form_login:
                login_path: login
                check_path: login
                
                failure_handler: login_failure_handler
                
            logout:
                path: /logout
                target: base_front
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # 1 week in seconds
                path: /
                domain: ~  # Defaults to the current domain from $_SERVER
                secure: false # Forces the session cookie to be sent only over HTTPS
                httponly: true # Forces the session cookie to be accessible only via the HTTP protocol and not in JavaScript

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
