security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Assuming 'email' is your unique identifier
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout
                target: app_login
            form_login:
                login_path: app_login  # Ensure you have a route named 'app_login'
                check_path: app_login  # Ensure this is also handled by your 'app_login' route
                default_target_path: /homeClient   # Set your desired URL here


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
