#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_modifier:
    path: /centre/modifier/{nom_centre}
    controller: 'App\Controller\CentreController::modifier'
    methods: ['GET', 'POST']

