services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    login_failure_handler:
        class: App\Security\LoginFailureHandler
        arguments:
            $router: '@router'
            $httpUtils: '@security.http_utils'
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    App\Security\LogoutSuccessHandler:
        class: App\Security\LogoutSuccessHandler
        arguments: 
            $logger: '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            - { name: 'kernel.event_subscriber' }
            - { name: 'logout_success_handler', method: 'onLogoutSuccess' }
