<?php

namespace ContainerHVxdxMU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T4Y6YwFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t4Y6YwF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t4Y6YwF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::request' => ['privates', '.service_locator.Atmz0tv', 'get_ServiceLocator_Atmz0tvService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.TIGO.0m', 'get_ServiceLocator_TIGO_0mService', true],
            'App\\Controller\\UserController::deleteUser' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.DXkG_Uv', 'get_ServiceLocator_DXkGUvService', true],
            'App\\Controller\\UserController::editUser' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController::edittest' => ['privates', '.service_locator.KkqsGdd', 'get_ServiceLocator_KkqsGddService', true],
            'App\\Controller\\UserController::generatePdfForUser' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.qiiGbg5', 'get_ServiceLocator_QiiGbg5Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\HomeController:request' => ['privates', '.service_locator.Atmz0tv', 'get_ServiceLocator_Atmz0tvService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.TIGO.0m', 'get_ServiceLocator_TIGO_0mService', true],
            'App\\Controller\\UserController:deleteUser' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.DXkG_Uv', 'get_ServiceLocator_DXkGUvService', true],
            'App\\Controller\\UserController:editUser' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController:edittest' => ['privates', '.service_locator.KkqsGdd', 'get_ServiceLocator_KkqsGddService', true],
            'App\\Controller\\UserController:generatePdfForUser' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.qiiGbg5', 'get_ServiceLocator_QiiGbg5Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\HomeController::request' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::deleteUser' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::editUser' => '?',
            'App\\Controller\\UserController::edittest' => '?',
            'App\\Controller\\UserController::generatePdfForUser' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\HomeController:request' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:deleteUser' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:editUser' => '?',
            'App\\Controller\\UserController:edittest' => '?',
            'App\\Controller\\UserController:generatePdfForUser' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
