<?php

namespace ContainerHVxdxMU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_L52UdVkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.l52UdVk' shared service.
     *
     * @return \App\Controller\MailerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\HomeController::request()": the $mailer argument is type-hinted with the non-existent class or interface: "App\\Controller\\MailerInterface". Did you forget to add a use statement?');
    }
}
