<?php

namespace ContainerHVxdxMU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Atmz0tvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Atmz0tv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Atmz0tv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', '.errored.l52UdVk', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::request()": the $mailer argument is type-hinted with the non-existent class or interface: "App\\Controller\\MailerInterface". Did you forget to add a use statement?'],
        ], [
            'mailer' => '?',
        ]);
    }
}
