<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHVxdxMU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHVxdxMU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHVxdxMU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHVxdxMU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHVxdxMU\App_KernelDevDebugContainer([
    'container.build_hash' => 'HVxdxMU',
    'container.build_id' => 'd732c2e5',
    'container.build_time' => 1714771279,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHVxdxMU');
